services:
  postgres:
    image: postgres:16.4
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local

volumes:
  redis-data:
  postgres-data:
